modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "overgrown_abyss"
version = "${version}"
displayName = "Overgrown Abyss"
authors = "syrval"
description = '''
A giant ravine leading down to a ruined jungle city
'''

[[dependencies.overgrown_abyss]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.overgrown_abyss]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.overgrown_abyss]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"
